FT.WEB/Controllers/HoldController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FT.DAL.Repositories;
using FT.Entities.Models;

namespace FT.WEB.Controllers
{
    public class HoldController : Controller
    {
        private FodboldTurneringDB db = new FodboldTurneringDB();

        // GET: Hold
        public ActionResult Index()
        {
            var holdListe = db.HoldListe.ToList();
            return View(holdListe);
        }

        // GET: Hold/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hold hold = db.HoldListe.Include(t => t.Turneringer).Where(h => h.HoldId == id).First();
            if (hold == null)
            {
                return HttpNotFound();
            }
            return View(hold);
        }

        // GET: Hold/Create
        public ActionResult Create()
        {
            ViewBag.TurneringId = new SelectList(db.Turneringer, "TurneringId", "Navn");
            return View();
        }

        // POST: Hold/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "HoldId,Navn,TurneringId")] Hold hold)
        {
            if (ModelState.IsValid)
            {
                db.HoldListe.Add(hold);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(hold);
        }

        // GET: Hold/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hold hold = db.HoldListe.Find(id);
            if (hold == null)
            {
                return HttpNotFound();
            }
            return View(hold);
        }

        // POST: Hold/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "HoldId,Navn,TurneringId")] Hold hold)
        {
            if (ModelState.IsValid)
            {
                db.Entry(hold).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(hold);
        }

        // GET: Hold/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hold hold = db.HoldListe.Find(id);
            if (hold == null)
            {
                return HttpNotFound();
            }
            return View(hold);
        }

        // POST: Hold/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Hold hold = db.HoldListe.Find(id);
            db.HoldListe.Remove(hold);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FT.WEB/Views/Hold/Create.cshtml
@model FT.Entities.Models.Hold

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Hold</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Navn, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Navn, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Navn, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FT.WEB/Views/Hold/Delete.cshtml
@model FT.Entities.Models.Hold

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Hold</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Turnering.Navn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Turnering.Navn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Navn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Navn)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

FT.WEB/Views/Hold/Details.cshtml
@model FT.Entities.Models.Hold

@{
    ViewBag.Title = "Details";
}

<br /><br />

@* Stamoplysninger for Hold *@
<div id="holdDetaljer">
    @Html.DisplayNameFor(model => model.Navn)
    @Html.EditorFor(model => model.Navn, new { htmlAttributes = new { @disabled = "dissabled" } })
    <a id="buttonRetHold" href="@Url.Action("Edit", "Hold", new { Id = Model.HoldId })">
        <i class="far fa-edit"></i>
        Ret
    </a>
</div>


<br />

@* Liste over turneringer som holdet er tilmeldt *@
<p>
    <strong>@Model.Navn</strong> er tilmeldt:
</p>

<div id="listeHoldTilmeldtTilTurneringer">
    @foreach (var turnering in Model.Turneringer)
    {
        <div id="tilmeldtTurnering">
            @turnering.Navn
        </div>
    }
</div>

FT.WEB/Views/Hold/Edit.cshtml
@model FT.Entities.Models.Hold

@{
    ViewBag.Title = "Edit";
}

<h2 class="text-center">Ret Hold</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.HoldId)

        <div class="form-group">
            <div class="col-md-offset-2">
                @Html.LabelFor(model => model.Navn, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.Navn, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Navn, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            <div class="col-md-offset-2">
                @Html.LabelFor(model => model.TurneringId, "TurneringId", htmlAttributes: new { @class = "control-label" })
                @Html.DropDownList("TurneringId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TurneringId, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2">
                <input type="submit" value="Gem" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div class="text-center">
    @Html.ActionLink("Holdoversigt", "Index", null, new { @class = "btn btn-primary" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FT.WEB/Views/Hold/Index.cshtml
@model IEnumerable<FT.Entities.Models.Hold>

@{
    ViewBag.Title = "Index";
}


<div id="holdIndexListe">
    @foreach (var item in Model)
    {
        <a id="hold" href='@(Url.Action("Details", "Hold", new { id = item.HoldId }))'>
            <i class="far fa-futbol"></i>
            @Html.DisplayFor(modelItem => item.Navn)
        </a>
    }
</div>

<br /><br />
<div class="text-center">
    <a class="btn btn-primary" href="@Url.Action("Create")">
        <i class="fas fa-plus"></i>
        Nyt Hold
    </a>
</div>