FT.WEB/Controllers/TurneringController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FT.DAL.Repositories;
using FT.Entities.Models;
using FT.Entities.ViewModels;
using Microsoft.Ajax.Utilities;

namespace FT.WEB.Controllers
{
    public class TurneringController : Controller
    {
        // REPOSITORY !!!
        private FodboldTurneringDB db = new FodboldTurneringDB();

        // GET: Turnering
        public ActionResult Index()
        {
            // REPOSITORY !!!
            return View(db.Turneringer.ToList());
        }

        // GET: Turnering/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            // REPOSITORY !!!
            Turnering turnering = db.Turneringer.Include(h => h.HoldListe).Include(k => k.Kampe).Where(d => d.TurneringId == id).First();
            if (turnering == null)
            {
                return HttpNotFound();
            }

            // if (turnering.HoldListe.Count >= turnering.MaxAntalHold || turnering.AabenForTilmelding == false)
            if (turnering.AabenForTilmelding == false)
            {
                return RedirectToAction("Kampprogram", new { turneringsId = turnering.TurneringId });
            }

            TurneringDetailsViewModel viewModel = OpbygTurneringDetailsViewModel(turnering);
            return View(viewModel);
        }

        public ActionResult StartTurnering(int? turneringsId)
        {
            // REPOSITORY !!!
            Turnering turnering = db.Turneringer.Include(h => h.HoldListe).Where(t => t.TurneringId == turneringsId).First();

            if (turnering.HoldListe.Count < 2)
            {
                return RedirectToAction("Details", new { id = turnering.TurneringId });
            }

            LukForTilmeldinger(turnering);

            UdregnKampprogram(turnering);

            GemKampprogram(turnering);

            return RedirectToAction("Kampprogram", new { turneringsId = turnering.TurneringId });
        }

        private KampprogramViewModel OpbygKampprogramViewModel(Turnering turnering)
        {
            List<Hold> holdTilmeldtTurnering = turnering.HoldListe.ToList();
            List<Kamp> kampe = turnering.Kampe.ToList();

            KampprogramViewModel viewModel = new KampprogramViewModel()
            {
                TurneringId = turnering.TurneringId,
                TurneringsNavn = turnering.Navn,
                HoldTilmeldtTurnering = holdTilmeldtTurnering,
                Kampe = kampe
            };
            
            return viewModel;
        }

        private void GemKampprogram(Turnering turnering)
        {
            db.SaveChanges();
        }

        public ActionResult Kampprogram(int? turneringsId = 0)
        {
            var turnering = new Turnering();
            if (turneringsId == 0)
            {
                // Hvis der ikke er valgt nogen turnering, så vælg den første
                turnering = db.Turneringer.Include(h => h.HoldListe).First();
                // for at finde kampe nedenfor sættes turneringsId til 
                // den første turnering, der blev fundet ovenfor
                turneringsId = turnering.TurneringId;
            } else
            {
                turnering = db.Turneringer.Include(h => h.HoldListe).Where(t => t.TurneringId == turneringsId).First();
            }
            
            ICollection<Kamp> kampe = db.Kampe.Include(h => h.HoldListe).Where(t => t.TurneringId == turneringsId).ToList();
            turnering.Kampe = kampe;
            KampprogramViewModel viewModel = OpbygKampprogramViewModel(turnering);
            return View(viewModel);
        }

        public void LukForTilmeldinger(Turnering turnering)
        {
            turnering.AabenForTilmelding = false;
            // REPOSITORY !!!
            db.SaveChanges();
        }

        private void UdregnKampprogram(Turnering turnering)
        {
            Hold[] holdListe = turnering.HoldListe.ToArray();
            int antalHold = holdListe.Count();
            int antalTurneringsRunder = BeregnAntalTurneringsRunder(antalHold);

            List<Hold> hjemmeHold, udeHold;
            FordelHjemmeOgUdehold(holdListe, antalHold, antalTurneringsRunder, out hjemmeHold, out udeHold);

            var antalKampePrRunde = antalHold / 2;
            List<Kamp> TurneringsRundeKampe = BeregnKampeForTurnering(turnering, antalTurneringsRunder, hjemmeHold, udeHold, antalKampePrRunde);
            turnering.Kampe = TurneringsRundeKampe;
        }

        private static List<Kamp> BeregnKampeForTurnering(Turnering turnering, int antalTurneringsRunder, List<Hold> hjemmeHold, List<Hold> udeHold, int antalKampePrRunde)
        {
            List<Kamp> TurneringsRundeKampe = new List<Kamp>();

            for (int j = 1; j <= antalTurneringsRunder; j++)
            {
                for (int i = 0; i < antalKampePrRunde; i++)
                {
                    Kamp kamp = new Kamp
                    {
                        TurneringId = turnering.TurneringId,
                        TurneringsRunde = j,
                        HoldListe = new List<Hold>
                        {
                            hjemmeHold[i],
                            udeHold[i]
                        },
                        ScoreHjemmeHold = "",
                        ScoreUdeHold = ""
                    };
                    TurneringsRundeKampe.Add(kamp);
                }

                OmrokerHjemmeOgUdeholdTilNaesteTurneringsRunde(hjemmeHold, udeHold);
            }

            return TurneringsRundeKampe;
        }

        private static void OmrokerHjemmeOgUdeholdTilNaesteTurneringsRunde(List<Hold> hjemmeHold, List<Hold> udeHold)
        {
            Hold foersteUdeHold = udeHold[0];
            udeHold.Remove(udeHold[0]);
            hjemmeHold.Insert(1, foersteUdeHold);

            Hold sidsteHjemmeHold = hjemmeHold[hjemmeHold.Count - 1];
            hjemmeHold.Remove(hjemmeHold[hjemmeHold.Count - 1]);
            udeHold.Insert(udeHold.Count, sidsteHjemmeHold);
        }

        private static void FordelHjemmeOgUdehold(Hold[] holdListe, int antalHold, int antalTurneringsRunder, out List<Hold> hjemmeHold, out List<Hold> udeHold)
        {
            hjemmeHold = new List<Hold>();
            udeHold = new List<Hold>();

            // fordel hjemme- og udehold
            int index = 0;
            while (index < antalTurneringsRunder)
            {
                hjemmeHold.Add(holdListe[index]);
                udeHold.Add(holdListe[index + 1]);
                index += 2;
            }
            if (antalHold % 2 != 0)
            {
                hjemmeHold.Add(holdListe[antalHold - 1]);
            }
        }

        private static int BeregnAntalTurneringsRunder(int antalHold)
        {
            int antalTurneringsRunder;
            if (antalHold % 2 != 0)
            {
                antalTurneringsRunder = antalHold;
            }
            else
            {
                antalTurneringsRunder = antalHold - 1;
            }

            return antalTurneringsRunder;
        }

        // GET: Turnering/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Turnering/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TurneringId,Navn,MaxAntalHold")] Turnering turnering)
        {
            if (ModelState.IsValid)
            {
                turnering.AabenForTilmelding = true;
                // REPOSITORY !!!
                db.Turneringer.Add(turnering);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(turnering);
        }

        // GET: Turnering/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            // REPOSITORY !!!
            Turnering turnering = db.Turneringer.Find(id);
            if (turnering == null)
            {
                return HttpNotFound();
            }
            return View(turnering);
        }

        // POST: Turnering/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TurneringId,Navn,MaxAntalHold,AabenForTilmelding")] Turnering turnering)
        {
            if (ModelState.IsValid)
            {
                db.Entry(turnering).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(turnering);
        }

        // GET: Turnering/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Turnering turnering = db.Turneringer.Find(id);
            if (turnering == null)
            {
                return HttpNotFound();
            }
            return View(turnering);
        }

        // POST: Turnering/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Turnering turnering = db.Turneringer.Find(id);

FT.WEB/Views/Turnering/Create.cshtml
@model FT.Entities.Models.Turnering

@{
    ViewBag.Title = "Create";
}

<h2 class="text-center">Opret en ny turnering</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <div class="col-md-offset-2">
                @Html.LabelFor(model => model.Navn, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.Navn, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Navn, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2">
                @Html.LabelFor(model => model.MaxAntalHold, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.MaxAntalHold, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaxAntalHold, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2">
                <input type="submit" value="Opret" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div class="text-center">
    @Html.ActionLink("Turneringer", "Index", null, new { @class = "btn btn-primary" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FT.WEB/Views/Turnering/Delete.cshtml
@model FT.Entities.Models.Turnering

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Turnering</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Navn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Navn)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.MaxAntalHold)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaxAntalHold)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

FT.WEB/Views/Turnering/Details.cshtml
@model FT.Entities.ViewModels.TurneringDetailsViewModel

<br /><br />

@Html.HiddenFor(model => model.Turnering.AabenForTilmelding)

@* Stamoplysninger for turnering *@
<div id="turneringsDetaljer">
    @Html.DisplayNameFor(model => model.Turnering.Navn)
    @Html.EditorFor(model => model.Turnering.Navn, new { htmlAttributes = new { @disabled = "disabled" } })
    @Html.DisplayNameFor(model => model.Turnering.MaxAntalHold)
    @Html.EditorFor(model => model.Turnering.MaxAntalHold, new { htmlAttributes = new { @disabled = "disabled" } })
    <a id="buttonRetTurnering" href="@Url.Action("Edit", "Turnering", new { Id = Model.Turnering.TurneringId })">
        <i class="far fa-edit"></i>
        Ret
    </a>
</div>


<br /><br />

@* Tilmeldte Hold *@
<div class="borderListe">
    <p class="text">
        Følgende hold er tilmeldt <strong>@Model.Turnering.Navn</strong> (klik på et hold for at afmelde det igen):
    </p>

    <div class="tilmeldteHoldListe">
        @foreach (var hold in Model.Turnering.HoldListe)
        {
            <a class="tilmeldtHold" href="@Url.Action("AfmeldHold","Turnering", new { turneringsId = Model.Turnering.TurneringId, holdId = hold.HoldId })">
                <i class="fas fa-minus"></i>
                @hold.Navn
            </a>
        }
    </div>
</div>


<br /><br />


@* Button: Start Turnering *@
<div class="text-center">
    <a id="buttonStartTurnering" href="@Url.Action("StartTurnering", "Turnering", new { turneringsId = Model.Turnering.TurneringId })">
        START TURNERING
    </a>
</div>

<br /><br />


@* Liste over Hold, der kan tilmeldes *@
<div class="borderListe">
    <p class="text">Klik på et hold nedenfor for at tilmelde det til <strong>@Model.Turnering.Navn</strong>:</p>
    <div id="ikkeTilmeldteHoldListe">
        @foreach (var hold in Model.IkkeTilmeldteHold)
        {
            <a class="ikkeTilmeldtHold" href="@Url.Action("TilmeldHold", "Turnering", new { turneringsId = Model.Turnering.TurneringId, holdId = hold.HoldId })">
                <i class="fas fa-plus"></i>
                @hold.Navn
            </a>
        }
    </div>
</div>

FT.WEB/Views/Turnering/Edit.cshtml
@model FT.Entities.Models.Turnering

@{
    ViewBag.Title = "Edit";
}

<h2 class="text-center">Ret Turnering</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.TurneringId)
    @Html.HiddenFor(model => model.AabenForTilmelding)

    <div class="form-group">
        <div class="col-md-offset-2">
            @Html.LabelFor(model => model.Navn, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.Navn, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Navn, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2">
            @Html.LabelFor(model => model.MaxAntalHold, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.MaxAntalHold, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MaxAntalHold, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2">
            <input type="submit" value="Gem" class="btn btn-primary" />
            @Html.ActionLink("Slet", "Delete", new { id = Model.TurneringId }, new { @class = "btn btn-danger" })
        </div>
    </div>
</div>
}


<div class="text-center">
    @Html.ActionLink("Turneringer", "Index", null, new { @class = "btn btn-primary" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FT.WEB/Views/Turnering/Index.cshtml
@model IEnumerable<FT.Entities.Models.Turnering>

@{
    ViewBag.Title = "Index";
}



<div id="turneringsIndexListe">
    @foreach (var item in Model)
    {
        <a id="turnering" href='@(Url.Action("Details", "Turnering", new { id = item.TurneringId }))'>
            <i class="far fa-futbol"></i>
            @Html.DisplayFor(modelItem => item.Navn)
        </a>
    }
</div>

<br /><br />

<div class="text-center">
    <a class="btn btn-primary" href="@Url.Action("Create")">
        <i class="fas fa-plus"></i>
        Ny Turnering
    </a>
</div>

@*
    <p>
        @Html.ActionLink("Ny Turnering", "Create", null, new { @class = "btn btn-primary" })
    </p>
*@

FT.WEB/Views/Turnering/Kampprogram.cshtml
@model FT.Entities.ViewModels.KampprogramViewModel

@{
    ViewBag.Title = "Kampprogram";
}
<p>
    <h2>KAMPPROGRAM</h2>
    <h3>@Model.TurneringsNavn</h3>
</p>


@* Liste over hold tilmeldt turneringen *@
<div class="tilmeldteHoldListe">
    @foreach (var hold in Model.HoldTilmeldtTurnering)
    {
        <div class="tilmeldtHold">
            @Html.DisplayFor(model => hold.Navn)
        </div>
    }
</div>

<br /><br />

@*<div id="listeKampe">*@
    @foreach (var kamp in Model.Kampe)
    {
        <div id="listeKampe">
            &nbsp;&nbsp;@kamp.TurneringsRunde. Runde
            <div>
                <span id="hjemmeHold">@Html.DisplayFor(model => kamp.HoldListe.ElementAt(0).Navn)</span>
                @Html.EditorFor(model => kamp.ScoreHjemmeHold)
                &nbsp;-&nbsp;
                @Html.EditorFor(model => kamp.ScoreUdeHold)
                <span id="udeHold">@Html.DisplayFor(model => kamp.HoldListe.ElementAt(1).Navn)</span>
            </div>
        </div>
    }
@*</div>*@